apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jmmd
  labels:
    type: local
spec:
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi