server:
  port: 8081
spring:
  application:
    name: product-service    
  cloud:
    config:
      import-check:
        enabled: false
eureka:
  client:
    service-url:
      localZone: http://localhost:8761/eureka
