apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "bootCampTest.fullname" . }}-test-connection"
  labels:
    {{- include "bootCampTest.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    port: {{ .Values.labels.ports.httpPort }}