apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-jmmd
  namespace: bootcamp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-jmmd
  template:
    metadata:
      labels:
        app: nginx-jmmd
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80