apiVersion: v1
kind: Service
metadata:
  name: service-jmmd
  namespace: bootcamp
spec:
  type: NodePort
  selector:
    app: nginx-jmmd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80