version: "3.7"

services:
    mariadb:
        image: mariadb
        container_name: mariadb_cont
        volumes:
            - C:\Users\josem\Desktop\Desarrollo\NTT DATA\Bootcamp\App\nttdatacenter-docker-t4-jmmd\data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
    wordpress:
        image: wordpress
        container_name: wordpress_cont
        depends_on:
            - mariadb
        environment:
            - WORDPRESS_DB_USER=root
            - WORDPRESS_DB_PASSWORD=root
            - WORDPRESS_DB_HOST=mariadb
        ports:
            - 8080:80

    