version: "3.7"

services:
  sonarqube:
    image: sonarquber_community_jmmd
    ports:
      - 9000:9000
    networks:
      - net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conff:/opt/sonarqube/conf
      - sonarqube_dataa:/opt/sonarqube/data
      - sonarqube_extensionss:/opt/sonarqube/extensions
      - sonarqube_bundled-pluginss:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    networks:
      - net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

networks:
  net:

volumes:
  sonarqube_conff:
  sonarqube_dataa:
  sonarqube_extensionss:
  sonarqube_bundled-pluginss: